### PR TITLE
ignore tags from other branches

### PR DESCRIPTION
**Pull request by masonkatz**
addresses issue #99 

TestOffBranchTags creates a repo with a master and develop branch, and alternates commits on the branches. The resulting changelog from the master branch should only have those versions/commits.

This is only a test that shows the issue.

### CODE REVIEW

**Comment by masonkatz** [comment]
Added potential fix to pull request as independent commit.

**Comment by masonkatz** [comment]
The ci commit is a throw away. I just wanted to demonstrate this pull requests passes the ci checks.

**Comment by caarlos0** [comment]
lgtm, can you rebase @masonkatz 

cc/ @djgilcrease as well

**Review by djgilcrease — APPROVED** [review]
LGTM

**Comment by djgilcrease** [comment]
Will never once the conflicts are resolved

**Comment by masonkatz** [comment]
Rebased

It looks like the ci is in flux right now -- see the linter failing on code outside of this commit.

**Pull request merged**
